import type { EnterpriseActionPlan, LoopRecommendation, UseCaseInput, UseCaseValidationResult } from "../types";

export function buildFirst30Days(recommendations: LoopRecommendation[], validation: UseCaseValidationResult): string[] {
  const primary = recommendations.filter((item) => item.role === "primary").slice(0, 4);
  const governance = recommendations.filter((item) => item.role === "governance").slice(0, 3);
  const validationLoops = recommendations.filter((item) => item.role === "validation").slice(0, 3);
  return [
    `Days 1-3: Confirm business outcome and scope for ${primary.map((item) => item.name).join(", ") || "the primary loop bundle"}.`,
    `Days 4-7: Assign named owners and evidence sources for ${governance.map((item) => item.name).join(", ") || "governance loops"}.`,
    `Days 8-14: Build the first proof packet with ${validationLoops.map((item) => item.name).join(", ") || "validation loops"}.`,
    "Days 15-21: Execute one bounded pilot event and record trigger, evidence, controls, verdict, and state transition.",
    `Days 22-30: Resolve readiness result ${validation.readiness} by closing gaps before standardizing or expanding.`,
  ];
}

export function buildEnterpriseActionPlan(
  input: UseCaseInput,
  recommendations: LoopRecommendation[],
  validation: UseCaseValidationResult,
): EnterpriseActionPlan {
  const first30Days = buildFirst30Days(recommendations, validation);
  const title = input.title || "Untitled enterprise use case";
  const summary = input.description || "No description supplied.";
  const markdown = [
    `# LoopOS Enterprise Action Plan: ${title}`,
    "",
    `Readiness: ${validation.readiness}`,
    `Corpus status: ${validation.corpusStatus}`,
    "",
    "## Business Outcome",
    "",
    input.businessOutcome || "Not supplied.",
    "",
    "## Recommended Loop Bundle",
    "",
    ...recommendations.slice(0, 12).map((item, index) => `${index + 1}. ${item.name} (${item.role}, ${item.risk_tier}) - ${item.factors[0]?.detail || "Matched by LoopOS metadata."}`),
    "",
    "## Validation Findings",
    "",
    ...validation.findings.map((item) => `- ${item.status.toUpperCase()}: ${item.label} - ${item.detail}`),
    "",
    "## First 30 Days",
    "",
    ...first30Days.map((item) => `- ${item}`),
    "",
    "## Trust Note",
    "",
    "This plan is generated by deterministic LoopOS metadata matching. It does not use hidden model confidence or post-hoc rationale.",
  ].join("\n");

  return {
    title,
    summary,
    recommendations,
    validation,
    first30Days,
    exportMarkdown: markdown,
  };
}
