"""Ed25519 verification against operator-pinned roots, with explicit test-only scope.

The operator must protect this trust configuration and the execution host outside
the assessed process. A signature authenticates assertions, not their truth.
"""
from __future__ import annotations

import base64
from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from .common import digest, encoded, require, AssuranceError
from .contracts import validate


def verify(envelope, trust, role, subject_sha, profile_sha, at, purpose):
    validate("envelope", envelope)
    validate("trust", trust)
    require(trust["issued_at"] <= at <= trust["expires_at"], "trust/revocation checkpoint is not current")
    body = envelope["body"]
    require(body["purpose"] == purpose and body["subject_sha"] == subject_sha and body["profile_sha"] == profile_sha,
            "wrong purpose, subject or profile")
    require(body["issued_at"] <= at < body["expires_at"], "expired or future evidence")
    require(body["expires_at"] - body["issued_at"] <= trust["max_ttl_seconds"], "excessive evidence TTL")
    require(envelope["issuer"] not in trust["revoked_issuers"], "revoked issuer")
    issuer = trust["issuers"].get(envelope["issuer"])
    require(issuer is not None and role in issuer["roles"], "untrusted issuer or role")
    require(issuer["valid_from"] <= body["issued_at"] < issuer["valid_until"] and at < issuer["valid_until"], "issuer validity ended")
    require(profile_sha in trust["approved_profiles"] and profile_sha not in trust["revoked_profiles"], "profile is not currently approved")
    require(body["invocation_id"] not in trust["revoked_invocations"], "revoked invocation")
    require(body["issued_at"] >= trust["evidence_not_before"], "evidence predates trustworthy checkpoint")
    try:
        key = Ed25519PublicKey.from_public_bytes(base64.b64decode(issuer["public_key"], validate=True))
        key.verify(base64.b64decode(envelope["signature"], validate=True), encoded(body))
    except (ValueError, InvalidSignature) as exc:
        raise AssuranceError("invalid evidence signature") from exc
    require(body["principal"] == issuer["principal"], "signer/principal mismatch")
    return issuer


def seal(body, issuer_id, key):
    """For protected collectors or test fixtures; keys are never generated by ingest."""
    return {"schema": "enterprise-envelope/v1", "issuer": issuer_id, "body": body,
            "signature": base64.b64encode(key.sign(encoded(body))).decode("ascii")}
